# Generated by Django 5.0.6 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('streams', '0002_streammeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushroute',
            name='source_player_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pushroute',
            name='relay_bitrate_kbps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pushroute',
            name='relay_uptime_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushroute',
            name='retry_in_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushroute',
            name='last_exit_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
